name: CxFlow

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.0-9.x
      with:
        project: CxFlowGithub-master
        team: '/CxServer/cx-scord'
        checkmarx_url: ${{ secrets.CX_SERVER }}        
        checkmarx_username: ${{secrets.CX_USER}}
        checkmarx_password: ${{secrets.CX_PASSWD}}
        checkmarx_client_secret: ${{secrets.CX_CLIENT_SECRET}}
        #app: Plus
        preset: 'High and Medium'
        # Break build based on Checkmarx findings?
        #break_build: # optional
        #incremental: true
        # github_token: ${{secrets.GITHUB_TOKEN}}
#         extra parameter
#         params: --bug-tracker=jira --config=cx.config --repo-
#         name=Orderweb --namespace= --branch=master --jira.url=${{secrets.JIRA_URL}} --jira.username=${{secrets.JIRA_USER}} --jira.
#         token=${{secrets.JIRA_TOKEN}}
##    - name: Upload SARIF file
##      uses: github/codeql-action/upload-sarif@v1
##      with:
##        sarif_file: cx.sarif
